CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS ltree;
CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE SCHEMA __schema__ AUTHORIZATION catalogowner;

CREATE TABLE __schema__.source (
    sourceid SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sourcecode TEXT NOT NULL UNIQUE,
    namezh TEXT NOT NULL,
    version TEXT NOT NULL,
    sourceurl TEXT NOT NULL,
    licensename TEXT NOT NULL,
    licenseurl TEXT,
    checksumsha256 TEXT NOT NULL,
    importedat TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE __schema__.source IS '公共地点数据来源及许可证信息';
COMMENT ON COLUMN __schema__.source.sourceid IS '数据来源内部编号';
COMMENT ON COLUMN __schema__.source.sourcecode IS '稳定来源代码，例如 geonames';
COMMENT ON COLUMN __schema__.source.namezh IS '数据来源中文名称';
COMMENT ON COLUMN __schema__.source.version IS '本次导入使用的数据版本';
COMMENT ON COLUMN __schema__.source.sourceurl IS '官方数据地址';
COMMENT ON COLUMN __schema__.source.licensename IS '许可证名称或使用条件说明';
COMMENT ON COLUMN __schema__.source.licenseurl IS '许可证说明地址';
COMMENT ON COLUMN __schema__.source.checksumsha256 IS '原始下载包 SHA256';
COMMENT ON COLUMN __schema__.source.importedat IS '数据导入时间';

CREATE TABLE __schema__.build (
    buildid UUID PRIMARY KEY,
    status TEXT NOT NULL CHECK (status IN ('running', 'completed', 'failed')),
    startedat TIMESTAMPTZ NOT NULL,
    finishedat TIMESTAMPTZ,
    counts JSONB NOT NULL DEFAULT '{}'::jsonb,
    details JSONB NOT NULL DEFAULT '{}'::jsonb,
    errormessage TEXT
);

COMMENT ON TABLE __schema__.build IS '地点目录每次构建的状态与统计';
COMMENT ON COLUMN __schema__.build.buildid IS '本次构建唯一编号';
COMMENT ON COLUMN __schema__.build.status IS '构建状态';
COMMENT ON COLUMN __schema__.build.startedat IS '构建开始时间';
COMMENT ON COLUMN __schema__.build.finishedat IS '构建结束时间';
COMMENT ON COLUMN __schema__.build.counts IS '各数据表记录数和质量统计';
COMMENT ON COLUMN __schema__.build.details IS '边界错误等可追溯构建明细';
COMMENT ON COLUMN __schema__.build.errormessage IS '失败时的安全错误摘要';

CREATE TABLE __schema__.location (
    locationid UUID PRIMARY KEY,
    kind TEXT NOT NULL CHECK (kind IN ('region', 'place', 'poi')),
    canonicalname TEXT NOT NULL,
    pointgeom geometry(Point, 4326),
    importance DOUBLE PRECISION NOT NULL DEFAULT 0,
    createdat TIMESTAMPTZ NOT NULL DEFAULT now(),
    updatedat TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE __schema__.location IS '行政区、自然地名和旅行地点的统一主体';
COMMENT ON COLUMN __schema__.location.locationid IS '跨数据库重建保持稳定的确定性 UUID';
COMMENT ON COLUMN __schema__.location.kind IS '地点类型：行政区、自然地名或旅行 POI';
COMMENT ON COLUMN __schema__.location.canonicalname IS '用于展示的主名称';
COMMENT ON COLUMN __schema__.location.pointgeom IS 'WGS-84 地点坐标';
COMMENT ON COLUMN __schema__.location.importance IS '用于同名结果排序的相对重要度';
COMMENT ON COLUMN __schema__.location.createdat IS '地点首次写入时间';
COMMENT ON COLUMN __schema__.location.updatedat IS '地点最近更新时间';

CREATE TABLE __schema__.locationsource (
    locationid UUID NOT NULL REFERENCES __schema__.location(locationid) ON DELETE CASCADE,
    sourceid SMALLINT NOT NULL REFERENCES __schema__.source(sourceid),
    sourcekey TEXT NOT NULL,
    rawname TEXT NOT NULL DEFAULT '',
    isprimary BOOLEAN NOT NULL DEFAULT false,
    PRIMARY KEY (sourceid, sourcekey),
    UNIQUE (locationid, sourceid, sourcekey)
);

COMMENT ON TABLE __schema__.locationsource IS '统一地点与一个或多个原始来源记录的映射';
COMMENT ON COLUMN __schema__.locationsource.locationid IS '统一地点编号';
COMMENT ON COLUMN __schema__.locationsource.sourceid IS '数据来源编号';
COMMENT ON COLUMN __schema__.locationsource.sourcekey IS '来源内部的稳定记录编号';
COMMENT ON COLUMN __schema__.locationsource.rawname IS '来源中的原始名称';
COMMENT ON COLUMN __schema__.locationsource.isprimary IS '该来源是否决定当前主数据';

CREATE TABLE __schema__.region (
    regionid UUID PRIMARY KEY REFERENCES __schema__.location(locationid) ON DELETE CASCADE,
    adcode CHAR(12) NOT NULL UNIQUE,
    parentid UUID REFERENCES __schema__.region(regionid) DEFERRABLE INITIALLY DEFERRED,
    level SMALLINT NOT NULL CHECK (level BETWEEN 0 AND 5),
    path LTREE NOT NULL UNIQUE,
    name TEXT NOT NULL,
    shortname TEXT NOT NULL DEFAULT '',
    pinyin TEXT NOT NULL DEFAULT '',
    pinyininitial TEXT NOT NULL DEFAULT '',
    status TEXT NOT NULL CHECK (status IN ('current', 'legacy', 'undetermined'))
);

COMMENT ON TABLE __schema__.region IS '以中国为根节点的省市区县乡镇村行政区树';
COMMENT ON COLUMN __schema__.region.regionid IS '行政区稳定 UUID，同时也是统一地点编号';
COMMENT ON COLUMN __schema__.region.adcode IS '右侧补零后的十二位行政区代码';
COMMENT ON COLUMN __schema__.region.parentid IS '直接上级行政区；中国根节点为空';
COMMENT ON COLUMN __schema__.region.level IS '行政层级：0 中国、1 省、2 地、3 县、4 乡、5 村';
COMMENT ON COLUMN __schema__.region.path IS '可索引的完整树路径';
COMMENT ON COLUMN __schema__.region.name IS '当前官方名称';
COMMENT ON COLUMN __schema__.region.shortname IS '不带常见行政后缀的简称';
COMMENT ON COLUMN __schema__.region.pinyin IS '来源提供的拼音';
COMMENT ON COLUMN __schema__.region.pinyininitial IS '拼音首字母';
COMMENT ON COLUMN __schema__.region.status IS '当前、历史或缺少新来源验证';

CREATE TABLE __schema__.locationname (
    nameid BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    locationid UUID NOT NULL REFERENCES __schema__.location(locationid) ON DELETE CASCADE,
    sourceid SMALLINT REFERENCES __schema__.source(sourceid),
    name TEXT NOT NULL,
    normalizedname TEXT NOT NULL,
    nametype TEXT NOT NULL CHECK (nametype IN ('official', 'short', 'pinyin', 'alternate', 'historical')),
    languagecode TEXT NOT NULL DEFAULT '',
    priority SMALLINT NOT NULL DEFAULT 0,
    UNIQUE (locationid, normalizedname, nametype, languagecode)
);

COMMENT ON TABLE __schema__.locationname IS '地点的官方名、简称、拼音、英文名和其他别名';
COMMENT ON COLUMN __schema__.locationname.nameid IS '名称记录内部编号';
COMMENT ON COLUMN __schema__.locationname.locationid IS '名称指向的统一地点';
COMMENT ON COLUMN __schema__.locationname.sourceid IS '名称来源，系统生成简称时可以为空';
COMMENT ON COLUMN __schema__.locationname.name IS '原始可展示名称';
COMMENT ON COLUMN __schema__.locationname.normalizedname IS '去除空格标点并小写后的检索名称';
COMMENT ON COLUMN __schema__.locationname.nametype IS '官方名、简称、拼音、其他名或历史名';
COMMENT ON COLUMN __schema__.locationname.languagecode IS '语言代码，来源未知时为空';
COMMENT ON COLUMN __schema__.locationname.priority IS '同名候选排序优先级';

CREATE TABLE __schema__.geoplace (
    locationid UUID PRIMARY KEY REFERENCES __schema__.location(locationid) ON DELETE CASCADE,
    geonameid BIGINT NOT NULL UNIQUE,
    asciiname TEXT NOT NULL DEFAULT '',
    featureclass CHAR(1) NOT NULL,
    featurecode TEXT NOT NULL,
    countrycode CHAR(2) NOT NULL,
    admin1 TEXT NOT NULL DEFAULT '',
    admin2 TEXT NOT NULL DEFAULT '',
    admin3 TEXT NOT NULL DEFAULT '',
    admin4 TEXT NOT NULL DEFAULT '',
    population BIGINT NOT NULL DEFAULT 0,
    elevation INTEGER,
    dem INTEGER,
    timezone TEXT NOT NULL DEFAULT '',
    modifiedon DATE
);

COMMENT ON TABLE __schema__.geoplace IS 'GeoNames 中国文件中的完整地理实体';
COMMENT ON COLUMN __schema__.geoplace.locationid IS '统一地点编号';
COMMENT ON COLUMN __schema__.geoplace.geonameid IS 'GeoNames 官方记录编号';
COMMENT ON COLUMN __schema__.geoplace.asciiname IS 'GeoNames ASCII 名称';
COMMENT ON COLUMN __schema__.geoplace.featureclass IS 'GeoNames 地理要素大类';
COMMENT ON COLUMN __schema__.geoplace.featurecode IS 'GeoNames 地理要素代码';
COMMENT ON COLUMN __schema__.geoplace.countrycode IS '国家或地区代码';
COMMENT ON COLUMN __schema__.geoplace.admin1 IS 'GeoNames 一级行政代码';
COMMENT ON COLUMN __schema__.geoplace.admin2 IS 'GeoNames 二级行政代码';
COMMENT ON COLUMN __schema__.geoplace.admin3 IS 'GeoNames 三级行政代码';
COMMENT ON COLUMN __schema__.geoplace.admin4 IS 'GeoNames 四级行政代码';
COMMENT ON COLUMN __schema__.geoplace.population IS '人口数，来源缺失时为零';
COMMENT ON COLUMN __schema__.geoplace.elevation IS '来源提供的海拔';
COMMENT ON COLUMN __schema__.geoplace.dem IS '数字高程模型高度';
COMMENT ON COLUMN __schema__.geoplace.timezone IS '时区名称';
COMMENT ON COLUMN __schema__.geoplace.modifiedon IS 'GeoNames 记录更新时间';

CREATE TABLE __schema__.poi (
    locationid UUID PRIMARY KEY REFERENCES __schema__.location(locationid) ON DELETE CASCADE,
    elementtype TEXT NOT NULL CHECK (elementtype IN ('node', 'way', 'relation')),
    elementid BIGINT NOT NULL,
    category TEXT NOT NULL CHECK (category IN ('attraction', 'restaurant', 'hotel')),
    typename TEXT NOT NULL DEFAULT '',
    address TEXT NOT NULL DEFAULT '',
    imageurl TEXT,
    sourceadcode CHAR(12),
    sourceurl TEXT NOT NULL,
    UNIQUE (elementtype, elementid)
);

COMMENT ON TABLE __schema__.poi IS '从 OpenStreetMap 提取的旅行相关地点';
COMMENT ON COLUMN __schema__.poi.locationid IS '统一地点编号';
COMMENT ON COLUMN __schema__.poi.elementtype IS 'OSM 元素类型';
COMMENT ON COLUMN __schema__.poi.elementid IS 'OSM 元素编号';
COMMENT ON COLUMN __schema__.poi.category IS '景点、餐饮或住宿分类';
COMMENT ON COLUMN __schema__.poi.typename IS 'OSM 原始类型标签';
COMMENT ON COLUMN __schema__.poi.address IS '可用地址标签组合';
COMMENT ON COLUMN __schema__.poi.imageurl IS '合法 HTTP(S) 图片地址';
COMMENT ON COLUMN __schema__.poi.sourceadcode IS 'OSM 明确提供的十二位国标行政区代码';
COMMENT ON COLUMN __schema__.poi.sourceurl IS 'OpenStreetMap 原始记录链接';

CREATE TABLE __schema__.boundary (
    regionid UUID PRIMARY KEY REFERENCES __schema__.region(regionid) ON DELETE CASCADE,
    sourceid SMALLINT NOT NULL REFERENCES __schema__.source(sourceid),
    centergeom geometry(Point, 4326),
    boundarygeom geometry(MultiPolygon, 4326),
    originalsystem TEXT NOT NULL,
    conversionmethod TEXT NOT NULL
);

COMMENT ON TABLE __schema__.boundary IS '行政区中心点和多边形边界';
COMMENT ON COLUMN __schema__.boundary.regionid IS '边界所属行政区';
COMMENT ON COLUMN __schema__.boundary.sourceid IS '边界数据来源';
COMMENT ON COLUMN __schema__.boundary.centergeom IS '转换后的 WGS-84 中心点';
COMMENT ON COLUMN __schema__.boundary.boundarygeom IS '转换并修复后的 WGS-84 多边形';
COMMENT ON COLUMN __schema__.boundary.originalsystem IS '原始坐标系，当前为 GCJ-02';
COMMENT ON COLUMN __schema__.boundary.conversionmethod IS '坐标转换算法说明';

CREATE TABLE __schema__.regionmatch (
    locationid UUID PRIMARY KEY REFERENCES __schema__.location(locationid) ON DELETE CASCADE,
    regionid UUID REFERENCES __schema__.region(regionid),
    matchmethod TEXT NOT NULL CHECK (matchmethod IN ('sourcecode', 'spatial', 'unmatched')),
    confidence NUMERIC(4, 3) NOT NULL CHECK (confidence BETWEEN 0 AND 1),
    matchedat TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (
        (matchmethod = 'unmatched' AND regionid IS NULL AND confidence = 0)
        OR (matchmethod <> 'unmatched' AND regionid IS NOT NULL)
    )
);

COMMENT ON TABLE __schema__.regionmatch IS '自然地名和 POI 挂接到行政树的结果';
COMMENT ON COLUMN __schema__.regionmatch.locationid IS '待挂接地点编号';
COMMENT ON COLUMN __schema__.regionmatch.regionid IS '确认的最深行政区，无法匹配时为空';
COMMENT ON COLUMN __schema__.regionmatch.matchmethod IS '来源代码、空间落区或未匹配';
COMMENT ON COLUMN __schema__.regionmatch.confidence IS '固定且可解释的匹配置信度';
COMMENT ON COLUMN __schema__.regionmatch.matchedat IS '执行匹配的时间';

-- catalogindexes
CREATE INDEX regionparentidx ON __schema__.region(parentid);
CREATE INDEX regionpathidx ON __schema__.region USING gist(path);
CREATE INDEX locationnameexactidx ON __schema__.locationname(normalizedname, priority DESC);
CREATE INDEX locationnametrigramidx ON __schema__.locationname USING gin(normalizedname gin_trgm_ops);
CREATE INDEX locationpointidx ON __schema__.location USING gist(pointgeom);
CREATE INDEX boundarygeomidx ON __schema__.boundary USING gist(boundarygeom);
CREATE INDEX locationsourceididx ON __schema__.locationsource(locationid);
CREATE INDEX regionmatchregionidx ON __schema__.regionmatch(regionid);
CREATE INDEX geoplacefeatureidx ON __schema__.geoplace(featureclass, featurecode);
CREATE INDEX poicategoryidx ON __schema__.poi(category);

GRANT USAGE ON SCHEMA __schema__ TO catalogreader;
GRANT SELECT ON ALL TABLES IN SCHEMA __schema__ TO catalogreader;
